version: "3"

services
  webserver:
    build: .
    dockerfile: Dockerfile
    container_name: ${WEBSERVER_NAME}
    volumes:
        - ./sites:/sites
    ports:
        - "${PORT}:80"
    restart: always
